### ISSUE TITLE
랜덤 맛집 뱃지를 포크로 바꾸기

### ISSUE THREAD

**Issue by metacode22** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#103]
## 📕 작업 설명

> 랜덤 맛집 뱃지를 포크로 바꾸기

## 📖 To-Do list

- [ ] 랜덤 맛집 뱃지를 포크로 바꾸기

**Comment by live-small** [comment]
굿! 이거 되면 진짜 재밌겠따
