### ISSUE TITLE
globalStyle theme, font 설정 

### ISSUE THREAD

**Issue by live-small** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#11]
## 📕 작업 설명

>  emotion 활용해서 globalStyle 설정 

## 고민 
뭐로 세팅할지 고민 -> 스타일과 컴포넌트를 분리하는 게 좋을 거 같아서 emotion으로 세팅진행하려다 팀원들에게 공유 -> emotion으로 세팅 확정

### emotion 
```javascript

const Header = () => {
  return <Test>HELLO WORLD</Test>;
};

export default Header;

const Test = styled(Box)`
  background-color: ${({ theme }) => theme.color.primary};
`;

```
- 장점: 컴포넌트랑 스타일을 분리 -> 보기 편함 
- 단점: theme에 지정해둔 스타일 변수 사용하고 싶으면, 작은 것도 다 스타일 컴포넌트 만들어서 해야함 

### chakra 
```javascript
const Header = () => {
  return <Test backgroundColor='color.primary'>HELLO WORLD</Test>;
};
```
- 장점: 한번에 작업할 수 있음 
- 단점: 스타일이 길어지면, 컴포넌트랑 스타일 분리가 안되어있어 가독성 떨어질 수 있음 

## 📖 To-Do list

- [x] globalStyle 세팅 - font 설정 
- [x] theme - main color, width등 변수로 관리 
- [ ] 웹폰트 세팅

**Comment by metacode22** [comment]
전자가 조금 더 낫다고 봐요! 정말 혹여나의 가능성이지만, chakra 말고 다른 ui 라이브러리를 쓰게 될 일이 생길 가능성이 더 높을 것 같은 반면, emotion을 styled-components로 바꾼다거나 하는 일은 적을 것 같아서요... ㅋㅋㅋㅋㅋ

그리고 전 jsx문 볼 때 스타일을 그렇게 궁금해하지 않는 편이기도 하구요. ㅎㅎㅎ
