### ISSUE TITLE
랜덤 맛집 뱃지를 커스텀 오버레이로 대체

### ISSUE THREAD

**Issue by metacode22** [prgrms-web-devcourse/Team-DarkNight-Kkini-FE#48]
## 📕 작업 설명

> 랜덤 맛집 뱃지를 커스텀 오버레이로 대체

## 📖 To-Do list

- [x] 랜덤 맛집 뱃지를 커스텀 오버레이로 대체
![image](https://user-images.githubusercontent.com/93233930/222137675-dec3451d-328e-4107-9b0e-77271364c931.png)

**Comment by live-small** [comment]
저걸 클릭하면 가게모달 UI가 뜨는건가요?

**Comment by metacode22** [comment]
넵 맞아요! 그렇게 되도록 구현해서 PR 올려뒀습니다.
